name: ğŸ“¦ Publish .NET Package - Keeper.SecretsManager.OracleKeyManagement

on:
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest  
    steps:
    - name: ğŸ“¥ Checkout repository
      uses: actions/checkout@v3

    - name: ğŸ”§ Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0' 

    - name: ğŸ“¦ Restore dependencies
      run: dotnet restore

    - name: ğŸ— Build solution
      run: dotnet build --configuration Release --no-restore

    - name: ğŸ“¦ Pack NuGet package
      run: dotnet pack --configuration Release --output ./nuget_packages

    - name: ğŸš€ Publish to NuGet.org
      run: dotnet nuget push ./nuget_packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json  --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}