name: Release HV Plugin

on:
  workflow_dispatch:
  push:
    tags:
      - 'vault-plugin-secrets-ksm/v*'

jobs:
  release-hv-plugin:
    environment: prod
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: integration/vault-plugin-secrets-ksm

    steps:

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      # Cache GoLang libs
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Install External Dependencies"
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y osslsigncode

      - name: "Retrieve secrets from KSM"
        id: ksmsecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_HASHICORP_VAULT_APP_CONFIG }}
          secrets: |
            9QY3bC2MXN-HaMMfpUHbGQ/file/keepersecurity.pfx > file:/tmp/keepersecurity.pfx
            9QY3bC2MXN-HaMMfpUHbGQ/custom_field/PFX Password > PASSPHRASE

      - name: "Fetch Go Dependencies"
        run: |
          go mod tidy

      - name: "Create binaries"
        run: | # initially `github.ref` == "ref/tags/vault-plugin-secrets-ksm/vX.Y.Z"
          PLUGIN_NAME="$(cut -d'/' -f3 <<<${{ github.ref }})"
          PLUGIN_VERSION="$(cut -d'/' -f4 <<<${{ github.ref }})"
          SIGNING_KEY="/tmp/keepersecurity.pfx"
          KEY_PASSPHRASE=${{ steps.ksmsecrets.outputs.PASSPHRASE }}
          echo "Plugin name: [${PLUGIN_NAME}]"
          echo "Plugin version: [${PLUGIN_VERSION:1}]"
          make release-all PLUGIN_NAME="${PLUGIN_NAME}" PLUGIN_VERSION="${PLUGIN_VERSION:1}" SIGNING_KEY="${SIGNING_KEY}" KEY_PASSPHRASE="${KEY_PASSPHRASE}"
        shell: bash

      - name: "Info: List created files"
        run: |
          pwd
          ls -la

      # Publish binaries
      - name: "Release Binaries"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: integration/vault-plugin-secrets-ksm/vault-plugin-secrets-ksm*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "KSM Hashicorp Vault Secrets Plugin ${{ github.ref }}"
