name: Test JavaScript Storage - AWS KMS

on:
  push:
    branches:
      - 'release/storage/javascript/aws-kms/**'
    paths:
      - 'sdk/javascript/packages/aws/**'
      - '.github/workflows/test.javascript.storage.aws.kms.yml'
  pull_request:
    branches:
      - 'release/storage/javascript/aws-kms/**'
    paths:
      - 'sdk/javascript/packages/aws/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk/javascript/packages/aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: sdk/javascript/packages/aws/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
