name: Test-Java-Storage-Oracle-KMS

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'sdk/java/storage/keeper_secrets_manager_storage_oracle_kms/**'
  push:
    branches: [ master ]
    paths:
      - 'sdk/java/storage/keeper_secrets_manager_storage_oracle_kms/**'
  workflow_dispatch:

jobs:
  test-java-storage-oracle-kms:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        java-version: [ '8', '11', '17' ]
    name: Test Oracle KMS Storage with Java ${{ matrix.java-version }}
    defaults:
      run:
        working-directory: ./sdk/java/storage/keeper_secrets_manager_storage_oracle_kms
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - name: Setup, Build and Test
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.9
          arguments: build test
          build-root-directory: ./sdk/java/storage/keeper_secrets_manager_storage_oracle_kms
